=== samuelrincon0196-glitch/25_26-LEMA-PROYECTOXML-Rincon-Mendez/plantilla/xsd/catalogo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="catalogo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="categoria" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="producto" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="precio">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:decimal">
                                                                    <xs:attribute name="moneda" type="xs:string" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="descuento" type="xs:integer"/>
                                                    <xs:element name="imagen" type="xs:string"/>
                                                    <xs:element name="url_ref" type="xs:anyURI"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:string" use="required"/>
                                                <xs:attribute name="stock" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nombre" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="fecha" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string" use="required"/>
            <xs:attribute name="cif" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>

</xs:schema>

=== samuelrincon0196-glitch/25_26-LEMA-PROYECTOXML-Rincon-Mendez/plantilla/xml/catalogo2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--COMIENZO
    DEL XML-->
<!--CONEXION CON EL
XSD-->
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/catalogo.xsd"
    nombre="TechSolution" cif="A12345678">

    <!--COMIENZO
        DEL CATALOGO-->
    <catalogo fecha="2025-26">

        <!--COMIENZO
            DE LA PRIMER CATEGORIA-->
        <categoria nombre="Componentes">
            <!--PRODUCTO
                1-->
            <producto id="p01" stock="si">
                <nombre>Tarjeta Gráfica RTX 4060</nombre>
                <precio moneda="EUR">320.00</precio>
                <descuento>10</descuento>
                <imagen>img/grafica.jpg</imagen>
                <url_ref>https://nvidia.com/rtx4060</url_ref>
            </producto>

            <!--PRODUCTO
                2-->
            <producto id="p02" stock="si">
                <nombre>Memoria RAM 16GB DDR5</nombre>
                <precio moneda="EUR">85.50</precio>
                <descuento>0</descuento>
                <imagen>img/ram.jpg</imagen>
                <url_ref>https://corsair.com/ram16</url_ref>
            </producto>

            <!--PRODUCTO
                3-->
            <producto id="p03" stock="no">
                <nombre>Procesador i7-13700K</nombre>
                <precio moneda="EUR">410.00</precio>
                <descuento>5</descuento>
                <imagen>img/cpu.jpg</imagen>
                <url_ref>https://intel.com/i7</url_ref>
            </producto>
        </categoria>
        <!--FIN
            DE LA PRIMERA CATEGORIA-->

        <!--COMIENZO
            DE LA SEGUNDA CATEGORIA-->
        <categoria nombre="Periféricos">

            <!--PRODUCTO
                1-->
            <producto id="p04" stock="si">
                <nombre>Teclado Mecánico RGB</nombre>
                <precio moneda="EUR">120.00</precio>
                <descuento>15</descuento>
                <imagen>img/teclado.jpg</imagen>
                <url_ref>https://logitech.com/mx-mechanical</url_ref>
            </producto>

            <!--PRODUCTO
                2-->
            <producto id="p05" stock="si">
                <nombre>Ratón Óptico 16000 DPI</nombre>
                <precio moneda="EUR">55.00</precio>
                <descuento>0</descuento>
                <imagen>img/raton.jpg</imagen>
                <url_ref>https://razer.com/deathadder</url_ref>
            </producto>

            <!--PRODUCTO
                3-->
            <producto id="p06" stock="si">
                <nombre>Monitor 27" 4K</nombre>
                <precio moneda="EUR">350.00</precio>
                <descuento>20</descuento>
                <imagen>img/monitor.jpg</imagen>
                <url_ref>https://dell.com/monitor4k</url_ref>
            </producto>
        </categoria>
        <!--FIN
            DE LA SEGUNDA CATEGORIA-->

    </catalogo>
    <!--FIN
        DEL CATALOGO-->
</empresa>
